export const TOP_PLAYERS = [
  // Argentina
  { id: 'arg-1', name: 'Lionel Messi', country: 'Argentina' },
  { id: 'arg-2', name: 'Lautaro Martínez', country: 'Argentina' },
  { id: 'arg-3', name: 'Julián Álvarez', country: 'Argentina' },
  { id: 'arg-4', name: 'Thiago Almada', country: 'Argentina' },
  { id: 'arg-5', name: 'Nicolás González', country: 'Argentina' },
  { id: 'arg-6', name: 'Nicolás Paz', country: 'Argentina' },
  { id: 'arg-7', name: 'Giuliano Simeone', country: 'Argentina' },
  { id: 'arg-8', name: 'Alexis Mac Allister', country: 'Argentina' },
  { id: 'arg-9', name: 'Enzo Fernández', country: 'Argentina' },
  { id: 'arg-10', name: 'Rodrigo De Paul', country: 'Argentina' },
  
  // Brasil
  { id: 'bra-1', name: 'Neymar', country: 'Brasil' },
  { id: 'bra-2', name: 'Vinícius Júnior', country: 'Brasil' },
  { id: 'bra-3', name: 'Raphinha', country: 'Brasil' },
  { id: 'bra-4', name: 'Endrick', country: 'Brasil' },
  { id: 'bra-5', name: 'Gabriel Martinelli', country: 'Brasil' },
  { id: 'bra-6', name: 'Matheus Cunha', country: 'Brasil' },
  { id: 'bra-7', name: 'Luiz Henrique', country: 'Brasil' },
  { id: 'bra-8', name: 'Bruno Guimarães', country: 'Brasil' },
  { id: 'bra-9', name: 'Lucas Paquetá', country: 'Brasil' },
  { id: 'bra-10', name: 'Casemiro', country: 'Brasil' },
  
  // Uruguay
  { id: 'uru-1', name: 'Darwin Núñez', country: 'Uruguay' },
  { id: 'uru-2', name: 'Rodrigo Aguirre', country: 'Uruguay' },
  { id: 'uru-3', name: 'Federico Viñas', country: 'Uruguay' },
  { id: 'uru-4', name: 'Facundo Pellistri', country: 'Uruguay' },
  { id: 'uru-5', name: 'Agustín Álvarez', country: 'Uruguay' },
  { id: 'uru-6', name: 'Federico Valverde', country: 'Uruguay' },
  { id: 'uru-7', name: 'Manuel Ugarte', country: 'Uruguay' },
  { id: 'uru-8', name: 'Nicolás De La Cruz', country: 'Uruguay' },
  { id: 'uru-9', name: 'Giorgian De Arrascaeta', country: 'Uruguay' },
  { id: 'uru-10', name: 'Brian Rodríguez', country: 'Uruguay' },
  
  // Colombia
  { id: 'col-1', name: 'Luis Díaz', country: 'Colombia' },
  { id: 'col-2', name: 'Jhon Durán', country: 'Colombia' },
  { id: 'col-3', name: 'Rafael Santos Borré', country: 'Colombia' },
  { id: 'col-4', name: 'Jhon Arias', country: 'Colombia' },
  { id: 'col-5', name: 'James Rodríguez', country: 'Colombia' },
  { id: 'col-6', name: 'Richard Ríos', country: 'Colombia' },
  { id: 'col-7', name: 'Juan Fernando Quintero', country: 'Colombia' },
  { id: 'col-8', name: 'Jorge Carrascal', country: 'Colombia' },
  { id: 'col-9', name: 'Marino Hinestroza', country: 'Colombia' },
  { id: 'col-10', name: 'Luis Sinisterra', country: 'Colombia' },
  
  // Francia
  { id: 'fra-1', name: 'Kylian Mbappé', country: 'Francia' },
  { id: 'fra-2', name: 'Ousmane Dembélé', country: 'Francia' },
  { id: 'fra-3', name: 'Michael Olise', country: 'Francia' },
  { id: 'fra-4', name: 'Bradley Barcola', country: 'Francia' },
  { id: 'fra-5', name: 'Marcus Thuram', country: 'Francia' },
  { id: 'fra-6', name: 'Rayan Cherki', country: 'Francia' },
  { id: 'fra-7', name: 'Désiré Doué', country: 'Francia' },
  { id: 'fra-8', name: 'Aurélien Tchouaméni', country: 'Francia' },
  { id: 'fra-9', name: 'Adrien Rabiot', country: 'Francia' },
  { id: 'fra-10', name: 'Warren Zaïre-Emery', country: 'Francia' },
  
  // Inglaterra
  { id: 'eng-1', name: 'Harry Kane', country: 'Inglaterra' },
  { id: 'eng-2', name: 'Bukayo Saka', country: 'Inglaterra' },
  { id: 'eng-3', name: 'Marcus Rashford', country: 'Inglaterra' },
  { id: 'eng-4', name: 'Ollie Watkins', country: 'Inglaterra' },
  { id: 'eng-5', name: 'Ivan Toney', country: 'Inglaterra' },
  { id: 'eng-6', name: 'Anthony Gordon', country: 'Inglaterra' },
  { id: 'eng-7', name: 'Jude Bellingham', country: 'Inglaterra' },
  { id: 'eng-8', name: 'Phil Foden', country: 'Inglaterra' },
  { id: 'eng-9', name: 'Eberechi Eze', country: 'Inglaterra' },
  { id: 'eng-10', name: 'Morgan Rogers', country: 'Inglaterra' },
  
  // España
  { id: 'esp-1', name: 'Lamine Yamal', country: 'España' },
  { id: 'esp-2', name: 'Nico Williams', country: 'España' },
  { id: 'esp-3', name: 'Álvaro Morata', country: 'España' },
  { id: 'esp-4', name: 'Ferran Torres', country: 'España' },
  { id: 'esp-5', name: 'Yeremy Pino', country: 'España' },
  { id: 'esp-6', name: 'Dani Olmo', country: 'España' },
  { id: 'esp-7', name: 'Pedri', country: 'España' },
  { id: 'esp-8', name: 'Gavi', country: 'España' },
  { id: 'esp-9', name: 'Rodri', country: 'España' },
  { id: 'esp-10', name: 'Fabián Ruiz', country: 'España' },
  
  // Alemania
  { id: 'ger-1', name: 'Jamal Musiala', country: 'Alemania' },
  { id: 'ger-2', name: 'Florian Wirtz', country: 'Alemania' },
  { id: 'ger-3', name: 'Kai Havertz', country: 'Alemania' },
  { id: 'ger-4', name: 'Leroy Sané', country: 'Alemania' },
  { id: 'ger-5', name: 'Deniz Undav', country: 'Alemania' },
  { id: 'ger-6', name: 'Niclas Füllkrug', country: 'Alemania' },
  { id: 'ger-7', name: 'Leon Goretzka', country: 'Alemania' },
  { id: 'ger-8', name: 'Pascal Groß', country: 'Alemania' },
  { id: 'ger-9', name: 'Aleksandar Pavlovic', country: 'Alemania' },
  { id: 'ger-10', name: 'Angelo Stiller', country: 'Alemania' },
  
  // Portugal
  { id: 'por-1', name: 'Cristiano Ronaldo', country: 'Portugal' },
  { id: 'por-2', name: 'Rafael Leão', country: 'Portugal' },
  { id: 'por-3', name: 'Gonçalo Ramos', country: 'Portugal' },
  { id: 'por-4', name: 'Pedro Neto', country: 'Portugal' },
  { id: 'por-5', name: 'Francisco Conceição', country: 'Portugal' },
  { id: 'por-6', name: 'João Félix', country: 'Portugal' },
  { id: 'por-7', name: 'Bruno Fernandes', country: 'Portugal' },
  { id: 'por-8', name: 'Bernardo Silva', country: 'Portugal' },
  { id: 'por-9', name: 'Vitinha', country: 'Portugal' },
  { id: 'por-10', name: 'João Neves', country: 'Portugal' },
  
  // Países Bajos
  { id: 'ned-1', name: 'Cody Gakpo', country: 'Países Bajos' },
  { id: 'ned-2', name: 'Memphis Depay', country: 'Países Bajos' },
  { id: 'ned-3', name: 'Donyell Malen', country: 'Países Bajos' },
  { id: 'ned-4', name: 'Noa Lang', country: 'Países Bajos' },
  { id: 'ned-5', name: 'Brian Brobbey', country: 'Países Bajos' },
  { id: 'ned-6', name: 'Frenkie de Jong', country: 'Países Bajos' },
  { id: 'ned-7', name: 'Xavi Simons', country: 'Países Bajos' },
  { id: 'ned-8', name: 'Tijjani Reijnders', country: 'Países Bajos' },
  { id: 'ned-9', name: 'Ryan Gravenberch', country: 'Países Bajos' },
  { id: 'ned-10', name: 'Teun Koopmeiners', country: 'Países Bajos' },
  
  // Bélgica
  { id: 'bel-1', name: 'Romelu Lukaku', country: 'Bélgica' },
  { id: 'bel-2', name: 'Jérémy Doku', country: 'Bélgica' },
  { id: 'bel-3', name: 'Loïs Openda', country: 'Bélgica' },
  { id: 'bel-4', name: 'Dodi Lukebakio', country: 'Bélgica' },
  { id: 'bel-5', name: 'Charles De Ketelaere', country: 'Bélgica' },
  { id: 'bel-6', name: 'Kevin De Bruyne', country: 'Bélgica' },
  { id: 'bel-7', name: 'Amadou Onana', country: 'Bélgica' },
  { id: 'bel-8', name: 'Youri Tielemans', country: 'Bélgica' },
  { id: 'bel-9', name: 'Johan Bakayoko', country: 'Bélgica' },
  { id: 'bel-10', name: 'Alexis Saelemaekers', country: 'Bélgica' },
  
  // Noruega
  { id: 'nor-1', name: 'Erling Haaland', country: 'Noruega' },
  { id: 'nor-2', name: 'Alexander Sørloth', country: 'Noruega' },
  { id: 'nor-3', name: 'Antonio Nusa', country: 'Noruega' },
  { id: 'nor-4', name: 'Oscar Bobb', country: 'Noruega' },
  { id: 'nor-5', name: 'Jørgen Strand Larsen', country: 'Noruega' },
  { id: 'nor-6', name: 'Martin Ødegaard', country: 'Noruega' },
  { id: 'nor-7', name: 'Sander Berge', country: 'Noruega' },
  { id: 'nor-8', name: 'Patrick Berg', country: 'Noruega' },
  { id: 'nor-9', name: 'Aron Dønnum', country: 'Noruega' },
  { id: 'nor-10', name: 'Andreas Schjelderup', country: 'Noruega' }
];
